<?php

namespace App\Services;

use Illuminate\Support\Arr;

class AnimalService
{
    public static function allForFilament() {
        $animals = self::all();

        return Arr::mapWithKeys($animals, function (string $item, int $key) {
            return [strtolower($item) => $item];
        });
    }

    public static function turkishForFilament() {
        $animals = self::turkish();

        return Arr::mapWithKeys($animals, function (string $item, string $key) {
            return [strtolower($key) => $item];
        });
    }

    public static function all() {
        return [
            "Aardvark",
            "Albatross",
            "Alligator",
            "Alpaca",
            "Ant",
            "Anteater",
            "Antelope",
            "Ape",
            "Armadillo",
            "Donkey",
            "Baboon",
            "Badger",
            "Barracuda",
            "Bat",
            "Bear",
            "Beaver",
            "Bee",
            "Bison",
            "Boar",
            "Buffalo",
            "Butterfly",
            "Camel",
            "Capybara",
            "Caribou",
            "Cassowary",
            "Cat",
            "Caterpillar",
            "Cattle",
            "Chamois",
            "Cheetah",
            "Chicken",
            "Chimpanzee",
            "Chinchilla",
            "Chough",
            "Clam",
            "Cobra",
            "Cockroach",
            "Cod",
            "Cormorant",
            "Coyote",
            "Crab",
            "Crane",
            "Crocodile",
            "Crow",
            "Curlew",
            "Deer",
            "Dinosaur",
            "Dog",
            "Dogfish",
            "Dolphin",
            "Dotterel",
            "Dove",
            "Dragonfly",
            "Duck",
            "Dugong",
            "Dunlin",
            "Eagle",
            "Echidna",
            "Eel",
            "Eland",
            "Elephant",
            "Elk",
            "Emu",
            "Falcon",
            "Ferret",
            "Finch",
            "Fish",
            "Flamingo",
            "Fly",
            "Fox",
            "Frog",
            "Gaur",
            "Gazelle",
            "Gerbil",
            "Giraffe",
            "Gnat",
            "Gnu",
            "Goat",
            "Goldfinch",
            "Goldfish",
            "Goose",
            "Gorilla",
            "Goshawk",
            "Grasshopper",
            "Grouse",
            "Guanaco",
            "Gull",
            "Hamster",
            "Hare",
            "Hawk",
            "Hedgehog",
            "Heron",
            "Herring",
            "Hippopotamus",
            "Hornet",
            "Horse",
            "Human",
            "Hummingbird",
            "Hyena",
            "Ibex",
            "Ibis",
            "Jackal",
            "Jaguar",
            "Jay",
            "Jellyfish",
            "Kangaroo",
            "Kingfisher",
            "Koala",
            "Kookabura",
            "Kouprey",
            "Kudu",
            "Lapwing",
            "Lark",
            "Lemur",
            "Leopard",
            "Lion",
            "Llama",
            "Lobster",
            "Locust",
            "Loris",
            "Louse",
            "Lyrebird",
            "Magpie",
            "Mallard",
            "Manatee",
            "Mandrill",
            "Mantis",
            "Marten",
            "Meerkat",
            "Mink",
            "Mole",
            "Mongoose",
            "Monkey",
            "Moose",
            "Mosquito",
            "Mouse",
            "Mule",
            "Narwhal",
            "Newt",
            "Nightingale",
            "Octopus",
            "Okapi",
            "Opossum",
            "Oryx",
            "Ostrich",
            "Otter",
            "Owl",
            "Oyster",
            "Panther",
            "Parrot",
            "Partridge",
            "Peafowl",
            "Pelican",
            "Penguin",
            "Pheasant",
            "Pig",
            "Pigeon",
            "Pony",
            "Porcupine",
            "Porpoise",
            "Quail",
            "Quelea",
            "Quetzal",
            "Rabbit",
            "Raccoon",
            "Rail",
            "Ram",
            "Rat",
            "Raven",
            "Red deer",
            "Red panda",
            "Reindeer",
            "Rhinoceros",
            "Rook",
            "Salamander",
            "Salmon",
            "Sand Dollar",
            "Sandpiper",
            "Sardine",
            "Scorpion",
            "Seahorse",
            "Seal",
            "Shark",
            "Sheep",
            "Shrew",
            "Skunk",
            "Snail",
            "Snake",
            "Sparrow",
            "Spider",
            "Spoonbill",
            "Squid",
            "Squirrel",
            "Starling",
            "Stingray",
            "Stinkbug",
            "Stork",
            "Swallow",
            "Swan",
            "Tapir",
            "Tarsier",
            "Termite",
            "Tiger",
            "Toad",
            "Trout",
            "Turkey",
            "Turtle",
            "Viper",
            "Vulture",
            "Wallaby",
            "Walrus",
            "Wasp",
            "Weasel",
            "Whale",
            "Wildcat",
            "Wolf",
            "Wolverine",
            "Wombat",
            "Woodcock",
            "Woodpecker",
            "Worm",
            "Wren",
            "Yak",
            "Zebra"
        ];
    }

    public static function turkish()
    {
        return [
            "Aardvark" => "Karınca Yiyen",
            "Albatross" => "Albatros",
            "Alligator" => "Timsah",
            "Alpaca" => "Alpaka",
            "Ant" => "Karınca",
            "Anteater" => "Karıncayiyen",
            "Antelope" => "Antilop",
            "Ape" => "İnsan Maymunu",
            "Armadillo" => "Armadillo",
            "Donkey" => "Eşek",
            "Baboon" => "Babun",
            "Badger" => "Porsuk",
            "Barracuda" => "Barakuda",
            "Bat" => "Yarasa",
            "Bear" => "Ayı",
            "Beaver" => "Kunduz",
            "Bee" => "Arı",
            "Bison" => "Bizon",
            "Boar" => "Yaban Domuzu",
            "Buffalo" => "Bufalo",
            "Butterfly" => "Kelebek",
            "Camel" => "Deve",
            "Capybara" => "Kapibara",
            "Caribou" => "Karibu",
            "Cassowary" => "Cassowary",
            "Cat" => "Kedi",
            "Caterpillar" => "Tırtıl",
            "Cattle" => "Sığır",
            "Chamois" => "Dağ Keçisi",
            "Cheetah" => "Çita",
            "Chicken" => "Tavuk",
            "Chimpanzee" => "Şempanze",
            "Chinchilla" => "Çinçila",
            "Chough" => "Karga",
            "Clam" => "Midye",
            "Cobra" => "Kobra",
            "Cockroach" => "Hamamböceği",
            "Cod" => "Morina Balığı",
            "Cormorant" => "Karabatak",
            "Coyote" => "Koyote",
            "Crab" => "Yengeç",
            "Crane" => "Turna",
            "Crocodile" => "Timsah",
            "Crow" => "Karga",
            "Curlew" => "Kervan Çulluğu",
            "Deer" => "Geyik",
            "Dinosaur" => "Dinozor",
            "Dog" => "Köpek",
            "Dogfish" => "Köpekbalığı",
            "Dolphin" => "Yunus",
            "Dotterel" => "Bozören Kuşu",
            "Dove" => "Güvercin",
            "Dragonfly" => "Helikopter Böceği",
            "Duck" => "Ördek",
            "Dugong" => "Dugong",
            "Dunlin" => "Küçük Kumkuşu",
            "Eagle" => "Kartal",
            "Echidna" => "Dikenli Karınca Yiyen",
            "Eel" => "Yılan Balığı",
            "Eland" => "Büyük Antilop",
            "Elephant" => "Fil",
            "Elk" => "Sığın",
            "Emu" => "Emu",
            "Falcon" => "Şahin",
            "Ferret" => "Gelincik",
            "Finch" => "İspinoz",
            "Fish" => "Balık",
            "Flamingo" => "Flamingo",
            "Fly" => "Sinek",
            "Fox" => "Tilki",
            "Frog" => "Kurbağa",
            "Gaur" => "Hint Mandası",
            "Gazelle" => "Ceylan",
            "Gerbil" => "Fare (Gerbil)",
            "Giraffe" => "Zürafa",
            "Gnat" => "Tatarcık",
            "Gnu" => "Gnu (Afrika Antilopu)",
            "Goat" => "Keçi",
            "Goldfinch" => "Saka Kuşu",
            "Goldfish" => "Japon Balığı",
            "Goose" => "Kaz",
            "Gorilla" => "Goril",
            "Goshawk" => "Çakırkuşu",
            "Grasshopper" => "Çekirge",
            "Grouse" => "Tetra Kuşu",
            "Guanaco" => "Guanako",
            "Gull" => "Martı",
            "Hamster" => "Hamster",
            "Hare" => "Tavşan",
            "Hawk" => "Şahin",
            "Hedgehog" => "Kirpi",
            "Heron" => "Balıkçıl",
            "Herring" => "Ringa Balığı",
            "Hippopotamus" => "Su Aygırı",
            "Hornet" => "Eşek Arısı",
            "Horse" => "At",
            "Human" => "İnsan",
            "Hummingbird" => "Sinek Kuşu",
            "Hyena" => "Sırtlan",
            "Ibex" => "Dağ Keçisi",
            "Ibis" => "İbis Kuşu",
            "Jackal" => "Çakal",
            "Jaguar" => "Jaguar",
            "Jay" => "Alakarga",
            "Jellyfish" => "Denizanası",
            "Kangaroo" => "Kanguru",
            "Kingfisher" => "Yalıçapkını",
            "Koala" => "Koala",
            "Kookabura" => "Kookabura",
            "Kouprey" => "Kouprey",
            "Kudu" => "Kudu",
            "Lapwing" => "Kızkuşu",
            "Lark" => "Tarla Kuşu",
            "Lemur" => "Lemur",
            "Leopard" => "Leopar",
            "Lion" => "Aslan",
            "Llama" => "Lama",
            "Lobster" => "Istakoz",
            "Locust" => "Çekirge",
            "Loris" => "Loris",
            "Louse" => "Bit",
            "Lyrebird" => "Leylek Kuşu",
            "Magpie" => "Saksağan",
            "Mallard" => "Yeşilbaş",
            "Manatee" => "Deniz İneği",
            "Mandrill" => "Mandril",
            "Mantis" => "Peygamber Devesi",
            "Marten" => "Sansar",
            "Meerkat" => "Mirket",
            "Mink" => "Vizon",
            "Mole" => "Köstebek",
            "Mongoose" => "Mangust",
            "Monkey" => "Maymun",
            "Moose" => "Geyik",
            "Mosquito" => "Sivrisinek",
            "Mouse" => "Fare",
            "Mule" => "Katır",
            "Narwhal" => "Deniz Gergedanı",
            "Newt" => "Semender",
            "Nightingale" => "Bülbül",
            "Octopus" => "Ahtapot",
            "Okapi" => "Okapi",
            "Opossum" => "Keseli Sıçan",
            "Oryx" => "Oryx",
            "Ostrich" => "Devekuşu",
            "Otter" => "Su Samuru",
            "Owl" => "Baykuş",
            "Oyster" => "İstiridye",
            "Panther" => "Panter",
            "Parrot" => "Papağan",
            "Partridge" => "Keklik",
            "Peafowl" => "Tavuskuşu",
            "Pelican" => "Pelikan",
            "Penguin" => "Penguen",
            "Pheasant" => "Sülün",
            "Pig" => "Domuz",
            "Pigeon" => "Güvercin",
            "Pony" => "Midilli",
            "Porcupine" => "Kirpi",
            "Porpoise" => "Yunus",
            "Quail" => "Bıldırcın",
            "Quelea" => "Afrika Dokumacı Kuşu",
            "Quetzal" => "Ketzal Kuşu",
            "Rabbit" => "Tavşan",
            "Raccoon" => "Rakum",
            "Rail" => "Su Tavuğu",
            "Ram" => "Koç",
            "Rat" => "Sıçan",
            "Raven" => "Kuzgun",
            "Red deer" => "Kızıl Geyik",
            "Red panda" => "Kırmızı Panda",
            "Reindeer" => "Ren Geyiği",
            "Rhinoceros" => "Gergedan",
            "Rook" => "Kuzgun",
            "Salamander" => "Semender",
            "Salmon" => "Somon Balığı",
            "Sand Dollar" => "Kum Doları",
            "Sandpiper" => "Düdükçün Kuşu",
            "Sardine" => "Sardalya",
            "Scorpion" => "Akrep",
            "Seahorse" => "Denizatı",
            "Seal" => "Fok",
            "Shark" => "Köpekbalığı",
            "Sheep" => "Koyun",
            "Shrew" => "Kör Fare",
            "Skunk" => "Porsuk",
            "Snail" => "Salyangoz",
            "Snake" => "Yılan",
            "Sparrow" => "Serçe",
            "Spider" => "Örümcek",
            "Spoonbill" => "Kaşıkçı Kuşu",
            "Squid" => "Kalamar",
            "Squirrel" => "Sincap",
            "Starling" => "Sığırcık",
            "Stingray" => "Vatoz",
            "Stinkbug" => "Kokuşmuş Böcek",
            "Stork" => "Leylek",
            "Swallow" => "Kırlangıç",
            "Swan" => "Kuğu",
            "Tapir" => "Tapir",
            "Tarsier" => "Tarsiyer",
            "Termite" => "Termit",
            "Tiger" => "Kaplan",
            "Toad" => "Kara Kurbağası",
            "Trout" => "Alabalık",
            "Turkey" => "Hindi",
            "Turtle" => "Kaplumbağa",
            "Viper" => "Engerek Yılanı",
            "Vulture" => "Akbaba",
            "Wallaby" => "Valabi",
            "Walrus" => "Mors",
            "Wasp" => "Eşek Arısı",
            "Weasel" => "Gelincik",
            "Whale" => "Balina",
            "Wildcat" => "Yaban Kedisi",
            "Wolf" => "Kurt",
            "Wolverine" => "Karayılan",
            "Wombat" => "Wombat",
            "Woodcock" => "Çulluk",
            "Woodpecker" => "Ağaçkakan",
            "Worm" => "Solucan",
            "Wren" => "Çalıkuşu",
            "Yak" => "Yak",
            "Zebra" => "Zebra"       
        ];
    }
}
